# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170504_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='Plop', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
